### PR TITLE
Fix version check on Node 10

### PR DESCRIPTION
**Pull request by skooda**
Fixes https://github.com/darkguy2008/parallelshell/issues/65

### CODE REVIEW

**Comment by Jab2870** [comment]
@darkguy2008 
Please merge this. Without this change, parallelshell is unusable

**Comment by Zewenaco** [comment]
Please guys merge this soon!!

**Comment by darkguy2008** [comment]
Done, thanks @skooda for your contribution! @Jab2870 @Zewenaco pleae confirm it's working. I've been busy with personal matters so I hadn't much time to check GitHub

**Comment by skooda** [comment]
Great .. please don't forget to release new version in NPM, thanks

**Pull request merged**
